### PR TITLE
Use latest version (5.4.2) of Lua

### PR DESCRIPTION
**Pull request by ryannair05**

### CODE REVIEW

**Comment by rweichler** [comment]
have u tested all the scripts?

**Comment by rweichler** [comment]
i like the `LUA_QL` stuff

**Comment by ryannair05** [comment]
Unfortunately, `LUA_QL` has been deprecated and no longer exists in newer versions of Lua

**Comment by ryannair05** [comment]
> have u tested all the scripts?

Update: The Burst, Helix, and Radar scripts do not work. The rest of the scripts have now been tested

**Comment by ryannair05** [comment]
> have u tested all the scripts?

I fixed the Helix and Radar Scripts, but unfortunately the Burst and Explosion ones are not working as the `translate` method no longer works

**Comment by ryannair05** [comment]
I have updated all the nonworking scripts, and they should be all working now!

**Comment by rweichler** [comment]
Ok this generally looks good. I am going to hold off merging this because I need to think if I want to update to Lua 5.4. Unlike other programming languages, with Lua, the newer versions aren't always better and I want to keep compatibility with [LuaJIT](https://luajit.org) which is frozen at a hybrid of Lua 5.1 and Lua 5.2. You can read some people's opinions here: https://old.reddit.com/r/lua/comments/2zutj8/mike_pall_luajit_dislikes_lua_53/

I appreciate the effort please don't make this discourage from trying more contributions, Lua version upgrades are a tricky subject and there is no right answer

**Pull request closed without merging**
